#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDc0MTIyZTM5N2YzZjI5ZWQyOWFlNjlhMGYzZGNkMGExNDRlZDI1YmUyZjBmNTgyYTE0ZWRjNWY5MGJkNmFiOTI5MTIxMDQyYTUyZjA4MmIxYzVhY2MyOGQ2OTAxOWZhMzg1Yw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
